---
- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster
  tags:
    - always


- name: Init Kubernetes cluster {{ master_ip }}
  when: reset_cluster is succeeded
  shell: |
    kubeadm init --pod-network-cidr={{ pod_network_cidr }} \
                 --apiserver-advertise-address {{ master_ip }}
  register: init_cluster
  environment:
    no_proxy: "$no_proxy,.svc,.svc.cluster.local"
  tags:
    - always


- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory
  tags:
    - always

- name: Copy admin.conf to Home directory
  when: init_cluster is succeeded
  copy:
    src: "{{ kubeadmin_config }}"
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 777
    remote_src: true
  tags:
    - always