---

# ####################################################################
#                             Prechecks
# ####################################################################

- name: Prechecks
  include_tasks: prechecks.yml
  tags:
    - always

# ####################################################################
#                             Prefilght
# ####################################################################

- name: Preflight
  include_tasks: preflight.yml
  tags:
    - always

# ####################################################################
#                             Install
# ####################################################################
- name: Install
  include_tasks: install.yml
  tags:
    - always

# ####################################################################
#                             Init
# ####################################################################
- name: Init
  include_tasks: init.yml
  tags:
    - always