apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  name: dns-server1
  namespace: dns
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: dns-server1-primary
      spec:
        pvc:
          selector:
            matchLabels:
              "kubernetes.io/hostname": "skyfarm"
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 10Gi
        source:
          http:
            url:
              "http://10.244.217.44:9000/public/focal-server-cloudimg-amd64.img"
  running: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vm: vm-datavolume
    spec:
      nodeSelector:
        "kubernetes.io/hostname": "skyfarm"
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: dns-server1-primary
            - disk:
                bus: virtio
              name: cloudinit
        machine:
          type: q35
        resources:
          requests:
            memory: 4Gi
      terminationGracePeriodSeconds: 0
      volumes:
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
                  user: ubuntu
                  password: "PoI456ZxC"
                  chpasswd: {expire: False}
                  ssh_authorized_keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjb7V327TTuP/A4aHOoqTi5/QIcnDBjBEvaeDiQwYoc7a5RmqT7YPtSpBQFGlkTPCxaL2uGPRbde5L7oMYfLTVT/8tzw1RdHT7h+rr2yAmcMy4op5crNBAsH9ov1nk5hh+xfVCrOVslpcUijS4YNuwAaPXg8w0u4yum03PpEgsYIvlvOIFdLYuIS10vCnZFi3R5d3eh4qujtp/W9p7BOkBwuGw78no07nNdsL34afdpyXD9gACtCJBpxFqbQr7S+LlQPbDX6WuFarPYgbT5VUnAf0n8uOBvm4nFHM/GpCFSKL04xanoy/RX6FtJfa+qV33EYH/HRNMDv6sjpvx0FUBs6s8vR//cI/MJIbOK9PgTKu40TKvHH3GnfocmZJhEO5AujM+7aOHOIvNRLpvBvfpmmZmRbHOI+ML6cQBIOsrokSIwkdhEZI/3mdT2Yw0mZ8yLxvCqpYTxT+rN9MYK1lAbf99BXvrbGqfvmKidi2JrgRyXf/bZDy9a+UkZ6X+ztE= moeid@moeid-IdeaPad-L340-17IRH-Gaming
          name: cloudinit
        - dataVolume:
            name: dns-server1-primary
          name: dns-server1-primary