---

- name: "install docker"
  apt:
    name: docker.io
  when: docker_package.changed 
  tags:
    - always

- name: "add your user to the docker group"
  shell: usermod -aG docker $USER
  tags:
    - always
- name: "change docker daemon"
  template:
        src: templates/daemon.json.j2
        dest: /etc/docker/daemon.json
  tags:
    - always

- name: "restart docker service and daemon"
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
    enabled: true
  tags:
    - always